[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:ttyd]
command=/usr/bin/ttyd -W -p %(ENV_PORT)s -i 0.0.0.0 tmux attach-session -t azmal
directory=/root
user=root
autostart=true
autorestart=true
startretries=10
stopasgroup=true
killasgroup=true
stdout_logfile=/tmp/ttyd.log
stderr_logfile=/tmp/ttyd-error.log
